"""MRM Assembler — merges multiple modules into a single report."""

from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import List

from .validator import MRMValidator

logger = logging.getLogger(__name__)


def assemble_report(input_dir: str, output_path: str, include_toc: bool = True) -> None:
    """Merge multiple MRM modules into a single Markdown report.

    Only files passing ``validate_directory`` are included. ``index.md`` is excluded.

    Args:
        input_dir: Directory containing MRM modules.
        output_path: Path to the final report.
        include_toc: Whether to generate a Table of Contents.
    """
    validator = MRMValidator(verbose=False)
    results = validator.validate_directory(input_dir)

    file_contents: List[dict] = []
    for result in sorted(results, key=lambda r: r.file_path):
        if "index.md" in result.file_path:
            continue

        # Use cached frontmatter
        fm = result.frontmatter
        if fm is None:
            logger.warning(f"Skipping file without frontmatter: {result.file_path}")
            continue

        try:
            with open(result.file_path, "r", encoding="utf-8") as fh:
                content = fh.read()
            _, body = validator.extract_frontmatter(content)
            file_contents.append(
                {
                    "title": str(fm.get("title", "Untitled")),
                    "id": str(fm.get("id", "")),
                    "body": body,
                    "path": result.file_path,
                }
            )
        except Exception as exc:
            logger.error(f"Error reading file {result.file_path}: {exc}")

    report = (
        f'---\n'
        f'title: "Complete Research Report"\n'
        f'author: "MRM Auto-Assembler"\n'
        f'date: "{datetime.now().strftime("%Y-%m-%d")}"\n'
        f'tags: [report, assembled]\n'
        f'---\n\n'
        f'# Complete Research Report\n\n'
        f'> **Generated by MRM Toolkit** |'
        f' {len(file_contents)} modules |'
        f' {datetime.now().strftime("%Y-%m-%d %H:%M")}\n\n'
    )

    if include_toc:
        report += "## Table of Contents\n\n"
        for i, fc in enumerate(file_contents, 1):
            anchor = fc["title"].replace(" ", "-").lower()
            report += f"{i}. [{fc['title']}](#{anchor})\n"
        report += "\n---\n\n"

    for fc in file_contents:
        report += f"\n## {fc['title']}\n"
        if fc["id"]:
            report += f"*File ID: `{fc['id']}`*\n"
        report += fc["body"]
        report += "\n---\n"

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(report)

    print(f"✅ Đã ghép báo cáo: {output_path} ({len(file_contents)} modules)")
