"""MRM Indexer — automatically generates index.md from MRM directory tree."""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from .validator import MRMValidator

logger = logging.getLogger(__name__)


def generate_index(
    directory: str, output_path: Optional[str] = None
) -> str:
    """Automatically generate index.md from MRM directory tree.

    Args:
        directory: Directory containing MRM files.
        output_path: Optional output path. Defaults to ``<directory>/index.md``.

    Returns:
        Generated index.md content.
    """
    md_count = len(list(Path(directory).rglob("*.md")))
    index_content = f"""---
id: index
title: "Research Index"
status: auto-generated
tags: [index, navigation]
summary: "Automatically generated index from MRM directory tree."
ai_context: "Used for navigation and understanding the overall research project structure."
---

# Research Index

> **TL;DR**: Overview of research documentation structure with {md_count} files.

## Directory Structure

```
"""

    # Directory tree
    tree_lines: List[str] = []
    for root, dirs, files in os.walk(directory):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        level = root.replace(directory, "").count(os.sep)
        indent = "│   " * level
        tree_lines.append(f"{indent}📁 {os.path.basename(root)}/")
        subindent = "│   " * (level + 1)
        for file in sorted(files):
            if file.endswith(".md"):
                tree_lines.append(f"{subindent}📄 {file}")

    index_content += "\n".join(tree_lines)
    index_content += "\n```\n\n## Files by Status\n\n"

    # Validate to get cached frontmatter
    validator = MRMValidator(verbose=False)
    results = validator.validate_directory(directory)

    status_groups: dict = {"draft": [], "review": [], "final": [], "unknown": []}

    for result in results:
        if "index.md" in result.file_path:
            continue

        # Use cached frontmatter
        fm = result.frontmatter
        if fm:
            status = str(fm.get("status", "unknown"))
            title = str(fm.get("title", os.path.basename(result.file_path)))
            file_id = str(fm.get("id", ""))
        else:
            status = "unknown"
            title = os.path.basename(result.file_path)
            file_id = ""

        target_group = status if status in status_groups else "unknown"
        status_groups[target_group].append((title, result.file_path, file_id))

    status_emoji = {"draft": "🟡", "review": "🟠", "final": "✅", "unknown": "⚪"}
    resolved_output = output_path or os.path.join(directory, "index.md")

    for status, files in status_groups.items():
        if not files:
            continue
        emoji = status_emoji.get(status, "")
        index_content += f"\n### {emoji} {status.upper()}\n\n"
        for title, path, file_id in sorted(files, key=lambda x: x[0]):
            rel_path = os.path.relpath(path, os.path.dirname(resolved_output))
            index_content += f"- [{title}]({rel_path})"
            if file_id:
                index_content += f" `[[{file_id}]]`"
            index_content += "\n"

    index_content += (
        f"\n---\n\n"
        f"*Automatically generated by MRM Toolkit on"
        f" {datetime.now().strftime('%Y-%m-%d %H:%M')}.*\n"
    )

    with open(resolved_output, "w", encoding="utf-8") as fh:
        fh.write(index_content)
    
    print(f"✅ Đã sinh index.md tại: {resolved_output}")

    return index_content
